version: "3.3"

services:
  db:
    image: lyubimovstudio-db:latest
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./docker/Dockerfile.db
    ports:
      - "5432:5432"
    networks:
      - postgres
    volumes:
      - dbdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - .env
    ports:
      - "9090:80"
    networks:
      - postgres
    volumes:
      - pgadmindata:/var/lib/pgadmin
      - ./docker/init/servers.json:/pgadmin4/servers.json

networks:
  postgres:

volumes:
  dbdata:
  pgadmindata:
