version: "3.3"

services:
  db:
    image: lyubimovroman/lyubimovstudio-db:latest
    env_file:
      - .env.prod
    build:
      context: .
      dockerfile: ./docker/Dockerfile.db
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - server

  api:
    image: lyubimovroman/lyubimovstudio-api:latest
    build:
      context: .
      dockerfile: ./docker/Dockerfile.api
    volumes:
      - uploads:/home/node/app/api/uploads
    depends_on:
      - db
    networks:
      - server

  ssr:
    image: lyubimovroman/lyubimovstudio-ssr:latest
    build:
      context: .
      dockerfile: ./docker/Dockerfile.ssr
    networks:
      - server

  server:
    image: lyubimovroman/lyubimovstudio-server:latest
    build:
      context: .
      dockerfile: ./docker/Dockerfile.server
    volumes:
      - uploads:/usr/share/nginx/html/uploads
    depends_on:
      - api
      - ssr
    networks:
      - server
    ports:
      - "80:80"

networks:
  server:

volumes:
  uploads:
    external: true
  dbdata:
  yarn_cache:
  node_modules_cache:
