version: "3.3"

services:
  db:
    image: lyubimovroman/lyubimovstudio-db:latest
    env_file:
      - .env.prod
    build:
      context: .
      dockerfile: ./docker/Dockerfile.db
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - server

  api:
    image: lyubimovroman/lyubimovstudio-api:latest
    build:
      context: .
      dockerfile: ./docker/Dockerfile.api
    volumes:
      - yarn_cache:/yarn
      - node_modules_cache:/home/node/app/node_modules
      - uploads:/home/node/app/api/uploads
    depends_on:
      - db
    networks:
      - server

  server:
    image: lyubimovroman/lyubimovstudio-server:latest
    build:
      context: .
      dockerfile: ./docker/Dockerfile.server
    volumes:
      - yarn_cache:/yarn
      - node_modules_cache:/home/node/app/node_modules
    depends_on:
      - api
    networks:
      - server
    ports:
      - "80:80"

networks:
  server:

volumes:
  uploads:
    external: true
  dbdata:
  yarn_cache:
  node_modules_cache:
