version: "3.3"

services:
  db:
    image: lyubimovstudio-db:latest
    ports:
      - "4000:5432"
    networks:
      - postgres
    volumes:
      - dbdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "9090:80"
    networks:
      - postgres
    volumes:
      - pgadmindata:/var/lib/pgadmin
      - ./docker/init/servers.json:/pgadmin4/servers.json
    environment:
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_DEFAULT_EMAIL: lubimov.nsk@gmail.com

networks:
  postgres:

volumes:
  dbdata:
  pgadmindata:
