FROM lyubimovstudio-build:latest as builder
FROM node:15.3.0-alpine

WORKDIR /home/node/app

RUN mkdir -p /home/node/app/uploads

COPY --from=builder /home/node/app/dist/apps/api/package.json /home/node/app/package.json
RUN yarn install --no-lockfile
RUN yarn add pg --no-lockfile
RUN yarn add passport --no-lockfile
RUN yarn cache clean

COPY --from=builder /home/node/app/dist/apps/api /home/node/app/

COPY .prod.env ./.env

CMD node main.js --enable-source-maps

EXPOSE 3333
