FROM node:15.3.0 AS builder

WORKDIR /

COPY angular.json babel.config.json decorate-angular-cli.js nx.json tsconfig.base.json ./
COPY package.json yarn.lock ./
RUN yarn

COPY libs libs/

COPY apps/api ./apps/api/

RUN yarn nx build api --prod
