
FROM lyubimovstudio-build:latest as builder
FROM nginx:stable

COPY docker/init/site.req.pem /usr/local/share/ca-certificates/site.crt
COPY docker/init/site.key.pem /etc/ssl/private/site.key
RUN update-ca-certificates

COPY docker/init/nginx.conf /etc/nginx/conf.d/default.conf

COPY --from=builder /home/node/app/dist/apps/client /usr/share/nginx/html/client/
COPY --from=builder /home/node/app/dist/apps/admin /usr/share/nginx/html/admin/

EXPOSE 80 443

CMD ["nginx", "-g", "daemon off;"]
